package:
  name: yt
  version: 4.0_dev

source:
  git_url: http://github.com/yt-project/yt
  git_rev: master  

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - h5py
    

about:
  home: http://yt-project.org
  license: BSD
