package:
  name: soxs
  version: 1.3.0

source:
  fn: soxs-1.3.0.tar.gz
  url: https://pypi.python.org/packages/b2/3e/2a8e7910eb168f223d55e389538b0a6958c86a60d4fb05948756d242db4f/soxs-1.3.0.post1.tar.gz#md5=cd464d82d550254877560446114ed747
  md5: cd464d82d550254877560446114ed747

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - pyregion

about:
  home: 
  license: BSD
