package:
  name: soxs
  version: 2.3.0

source:
  fn: soxs-2.3.0.tar.gz
  url: https://files.pythonhosted.org/packages/09/80/9feb30786304d810c6402b25fda105499cb75fc9a58e2a3b7d4247f44943/soxs-2.3.0.tar.gz
  sha256: 49a03c62aba8653d7c52c2c9b10ea05e83e1fbe6d6cc535c860475ad2f8eaab7

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - pyregion

about:
  home: 
  license: BSD
