package:
  name: soxs
  version: 2.1.0

source:
  fn: soxs-2.1.0.tar.gz
  url: https://files.pythonhosted.org/packages/4a/ae/f27e649768b20db17a1ee5520f1aedf8abbe673caaef26712200a8a71aeb/soxs-2.1.0.tar.gz
  sha256: ef3adf01d9e002d8e696533aa6d3f79a9e8bf67819c6f7b087dc19fe71e93e41

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - pyregion

about:
  home: 
  license: BSD
