package:
  name: soxs
  version: 2.2.0

source:
  fn: soxs-2.2.0.post1.tar.gz
  url: https://files.pythonhosted.org/packages/46/d8/e87c4056b83afef60a4f11d6c0a0676b396a478d92d69bcf15d125abfd65/soxs-2.2.0.post1.tar.gz
  sha256: 3f88b51396fbf077c8e6a3bbc51d8f21fb2312b72c698aa21c154ddc15a3e287

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - pyregion

about:
  home: 
  license: BSD
