package:
  name: soxs
  version: 2.0.0

source:
  fn: soxs-2.0.0.tar.gz
  url: https://pypi.python.org/packages/e0/1f/7eea1a5de09be1b15c4c0528931aa9231eb67cde023358161a457bbb3a72/soxs-2.0.0.tar.gz#md5=36ca3a473735bfa3ea1b3701bfb18f8b
  md5: 36ca3a473735bfa3ea1b3701bfb18f8b

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - pyregion

about:
  home: 
  license: BSD
