package:
  name: soxs
  version: 2.1.0

source:
  fn: soxs-2.1.0.post1.tar.gz
  url: https://files.pythonhosted.org/packages/97/29/11d06ff66d170fc903d2258163994906575198566ab7d47c1ce82af72085/soxs-2.1.0.post1.tar.gz
  sha256: b245b4663b77ac915f2555817af4df53970c99e1b7ed43b1bf98e919444146d0

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - pyregion

about:
  home: 
  license: BSD
