package:
  name: soxs
  version: 3.0.0

source:
  fn: soxs-3.0.0.tar.gz
  url: https://files.pythonhosted.org/packages/03/40/fc5dd2de091a690dd08a37ea0328c149040b4c5c27b6d2bcc83a993b8dac/soxs-3.0.0.tar.gz
  sha256: d3dd9c41324ed1abce42ed43af0c26ed4eb36f885a23eaa94f0e642958a6ecd5

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - regions
    - appdirs
    - scipy
    - pooch
    
about:
  home: 
  license: BSD
