package:
  name: soxs
  version: 2.2.0

source:
  fn: soxs-2.2.0.tar.gz
  url: https://files.pythonhosted.org/packages/f6/91/edfdecacb81f5e4b9e3c060c4b2739ef83d867584f426fcf6e266fab1785/soxs-2.2.0.tar.gz
  sha256: a3591e3ff6a6dccdc840b53ecf07cdf05b6af77bf46630a92299050120602e28

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - pyregion

about:
  home: 
  license: BSD
