package:
  name: soxs
  version: 0.6_dev

source:
  git_url: http://github.com/XRStools/soxs
  git_rev: master

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy

about:
  home: 
  license: BSD
