package:
  name: pyxsim
  version: 2.0.0

source:
  fn: pyxsim-2.0.0.tar.gz
  url: https://pypi.python.org/packages/c2/fb/9c6b551a8b0048ff81d96d55c989b955e549fcde8bb607b51e7b31cd1af3/pyxsim-2.0.0.tar.gz#md5=08c58a9232157fd5a8f7f75370c3841e
  md5: 08c58a9232157fd5a8f7f75370c3841e

requirements:
  build:
    - python
    - numpy
    - setuptools
  run:
    - python
    - numpy
    - h5py
    - astropy
    - yt
    - soxs

about:
  home: http://hea-www.cfa.harvard.edu/~jzuhone/pyxsim
  license: BSD
