package:
  name: pyxsim
  version: 2.3.1

source:
  fn: pyxsim-2.3.1.tar.gz
  url: https://files.pythonhosted.org/packages/68/97/a9a5b0fd942b338be0e70ad168c37135def0a04950649cc7bbf045112bc1/pyxsim-2.3.1.tar.gz
  sha256: 8b4b6079f2d7f16d8805e81aaeac255571d9e36c4941d2fb8736d38ccddef0b2

requirements:
  build:
    - python
    - numpy
    - setuptools
    - cython
  run:
    - python
    - numpy
    - h5py
    - astropy
    - yt
    - soxs

about:
  home: http://hea-www.cfa.harvard.edu/~jzuhone/pyxsim
  license: BSD
