package:
  name: pyxsim
  version: 2.3.0

source:
  fn: pyxsim-2.3.0.tar.gz
  url: https://files.pythonhosted.org/packages/a1/3d/7aa64f0b4f78a24eaeac584287686c60a8efd1e49347201a48a5b1cd7c87/pyxsim-2.3.0.tar.gz
  sha256: c296de857155e3cb3b7a73b586f3129ab8a8d8460ad01d442b7befba6eea2fe1

requirements:
  build:
    - python
    - numpy
    - setuptools
    - cython
  run:
    - python
    - numpy
    - h5py
    - astropy
    - yt
    - soxs

about:
  home: http://hea-www.cfa.harvard.edu/~jzuhone/pyxsim
  license: BSD
