package:
  name: pyxsim
  version: 2.2.0

source:
  fn: pyxsim-2.2.0.post2.tar.gz
  url: https://files.pythonhosted.org/packages/47/8f/edf4b70945818737510e224478471a61ad7470e264146f7a9221f4fa85f6/pyxsim-2.2.0.post2.tar.gz
  sha256: 5c1099e9be50bf89fe1804a193ae5ab54c76ed9d405ee457cc6f7b76ece8c7f2

requirements:
  build:
    - python
    - numpy
    - setuptools
    - cython
  run:
    - python
    - numpy
    - h5py
    - astropy
    - yt
    - soxs

about:
  home: http://hea-www.cfa.harvard.edu/~jzuhone/pyxsim
  license: BSD
