package:
  name: soxs
  version: 3.4.0

source:
  fn: soxs-3.4.0.tar.gz
  url: https://files.pythonhosted.org/packages/81/e9/6ca81d79f967729eca3f93e959e6c72abc6bff5ede7cd37c81e68d90740f/soxs-3.4.0.tar.gz
  sha256: fbea16ea40a2238503988892d06568cddf145aeee86942a05f3a3b6f6970d89b	

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - regions
    - appdirs
    - scipy
    - pooch
    
about:
  home: 
  license: BSD
