package:
  name: soxs
  version: 3.0.1

source:
  fn: soxs-3.0.1.post1.tar.gz
  url: https://files.pythonhosted.org/packages/53/44/5d5a43b6e0097ab1412d961decf41cb9e6a678cb7a6ca827c5b7ad9e2e4e/soxs-3.0.1.post1.tar.gz
  sha256: 11940343689f94b82c40926a3730da441d51b66ae719ccb7fae3d9e8cdbae9fa

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - regions
    - appdirs
    - scipy
    - pooch
    
about:
  home: 
  license: BSD
