package:
  name: soxs
  version: 3.2.0

source:
  fn: soxs-3.2.0.tar.gz
  url: https://files.pythonhosted.org/packages/63/f5/37a1137d9ea0fdd82c283bedfe54e68b6fc7a375f6bb4bf2ac9e6b06d10d/soxs-3.2.0.tar.gz
  sha256: 85525c786da932a9fc267fca9a88eb7315ef6a8fafdd79b519f75a3228a7b97b

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - regions
    - appdirs
    - scipy
    - pooch
    
about:
  home: 
  license: BSD
