
package:
  name: soxs
  version: 4.0b0

source:
  fn: soxs-4.0b0.tar.gz
  url: https://files.pythonhosted.org/packages/35/01/b40aa523fd9f6eecd36a80a0ddda3f8e8a18443922908fa938ae43647c7a/soxs-4.0b0.tar.gz
  sha256: 4c9cb1a757e56d8fa029b2bdf065968854ab184d3d9b9ca589ed2569c13e76e2

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools>=45
    - setuptools_scm[toml]>=6.2
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - regions
    - appdirs
    - scipy
    - pooch
    
about:
  home: 
  license: BSD
