package:
  name: soxs
  version: 3.0.2

source:
  fn: soxs-3.0.2.tar.gz
  url: https://files.pythonhosted.org/packages/03/ff/5647f240ef2fc97fa8c124eb1c539602de2f006baabf8ea531808b396a8b/soxs-3.0.2.tar.gz
  sha256: 4795a814eee713871821d3afa75c39b997466174c3931c73383695fafd7114ce

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - regions
    - appdirs
    - scipy
    - pooch
    
about:
  home: 
  license: BSD
