package:
  name: soxs
  version: 3.1.0

source:
  fn: soxs-3.1.0.post1.tar.gz
  url: https://files.pythonhosted.org/packages/6f/80/b4f9f773b15bfb6ed94affad6bf308af49417f886e0d11e5b1dba210a4e8/soxs-3.1.0.post1.tar.gz 
  sha256: bf66dd195bae4835c233f0a7adab4d7fdeb803109739d2e8631115f74f05e2a4

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - regions
    - appdirs
    - scipy
    - pooch
    
about:
  home: 
  license: BSD
