package:
  name: soxs
  version: 3.3.0

source:
  fn: soxs-3.3.0.tar.gz
  url: https://files.pythonhosted.org/packages/1d/42/bf2e5e423e5a535753f6feea0a6a6ca49698e3e558e50c7622f5f9b7cf90/soxs-3.3.0.tar.gz
  sha256: 1c911adac5bf2929675d39d1b1bbc2b096570b0457f1f43f5d10368e80ea86ae

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - regions
    - appdirs
    - scipy
    - pooch
    
about:
  home: 
  license: BSD
