
package:
  name: soxs
  version: 4.0.0

source:
  fn: soxs-4.0.0.tar.gz
  url: https://files.pythonhosted.org/packages/ff/1d/88fba51e41b7d2cf5f718c21459f952982b3461120d06bdb6e6b205015fb/soxs-4.0.0.tar.gz
  sha256: 5e585ed8ba4d90572660da8db48dd836dc4def415b30f31efd9e6ebb7c00d43e

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools>=45
    - setuptools_scm[toml]>=6.2
  run:
    - python
    - numpy
    - astropy
    - pyyaml
    - h5py
    - tqdm
    - regions
    - appdirs
    - scipy
    - pooch
    
about:
  home: 
  license: BSD
