package:
  name: pyxsim
  version: 4.0.1

source:
  fn: pyxsim-4.0.1.tar.gz
  url: https://files.pythonhosted.org/packages/65/83/d18e23447addf90c6d88d822830ad930f56b6ac557a7562a43358508b48c/pyxsim-4.0.1.tar.gz
  sha256: 87cd3566b67fa2b094e335422aea7b16c057fbd4aa3dcaf31d3f27f69f9bb28d

requirements:
  build:
    - python
    - numpy
    - setuptools
    - cython
  run:
    - python
    - numpy
    - h5py
    - astropy
    - yt>=4.1.2
    - soxs>=4.0.0
    - scipy
    - tqdm
    
about:
  home: http://hea-www.cfa.harvard.edu/~jzuhone/pyxsim
  license: BSD
