package:
  name: pyxsim
  version: 3.0.1

source:
  fn: pyxsim-3.0.1.tar.gz
  url: https://files.pythonhosted.org/packages/bc/31/2b84152172eb12fdd238ad42feca41f86b862ab9b041d098865fd4c64cb8/pyxsim-3.0.1.tar.gz
  sha256: c5ddd6f72878c13207cf44e15bd6dbbb62b73ad06e99c86b094020e762334512

requirements:
  build:
    - python
    - numpy
    - setuptools
    - cython
  run:
    - python
    - numpy
    - h5py
    - astropy
    - yt
    - soxs
    - scipy
    - tqdm
    
about:
  home: http://hea-www.cfa.harvard.edu/~jzuhone/pyxsim
  license: BSD
