package:
  name: pyxsim
  version: 3.0.0

source:
  fn: pyxsim-3.0.0.tar.gz
  url: https://files.pythonhosted.org/packages/c8/05/e5a700944ab240b1a0073fc4d7f81420e4d76bf03eb6796fe9c69b2a40a8/pyxsim-3.0.0.tar.gz
  sha256: d45d97f31b4522f58162169e76011f58cb028581c56033b67325202c1293874a

requirements:
  build:
    - python
    - numpy
    - setuptools
    - cython
  run:
    - python
    - numpy
    - h5py
    - astropy
    - yt
    - soxs
    - scipy
    - tqdm
    
about:
  home: http://hea-www.cfa.harvard.edu/~jzuhone/pyxsim
  license: BSD
